yarnPath: .yarn/releases/yarn-3.2.0.cjs
packageExtensions:
  "@gera2ld/plaid@*":
    dependencies:
      eslint-plugin-react: "*"
      eslint-plugin-react-hooks: "*"
      postcss: "*"
  "@gera2ld/plaid-rollup@*":
    dependencies:
      "@babel/core": "*"
      postcss: "*"
      "@babel/plugin-transform-runtime": "*"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"